### ISSUE TITLE
Crashing App on Workshop and devsprint button!

### ISSUE THREAD

**Issue by philo-math** [pythonindia/PyCon-Mobile-App#93]
App is crashing at various times which is documented here with the present python libraries and error produced.
```
(kivy_apps) [philomath@localhost PyCon-Mobile-App]$ pip -V
pip 10.0.1 from /home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/pip (python 2.7)

```
```
(kivy_apps) [philomath@localhost PyCon-Mobile-App]$ pip freeze
certifi==2018.4.16
chardet==3.0.4
Cython==0.28.3
docutils==0.14
idna==2.7
Kivy==1.10.0
Kivy-Garden==0.1.4
numpy==1.14.5
pygame==1.9.3
Pygments==2.2.0
requests==2.19.1
urllib3==1.23
```

Workshop and devsprint button on the home screen crashed the app with the following logs: 
```
(kivy_apps) [philomath@localhost PyCon-Mobile-App]$ python eventsapp/main.py -m screen:droid2,portrait -m inspector
[INFO   ] [Logger      ] Record log in /home/philomath/.kivy/logs/kivy_18-07-03_12.txt
[INFO   ] [Screen      ] Apply screen settings for Motorola Droid 2
[INFO   ] [Screen      ] size=480x854 dpi=240 density=1.5 orientation=portrait
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.15 (default, May 16 2018, 17:50:09) 
[GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[WARNING] [WinPygame   ] Video: failed (multisamples=2)
[WARNING] [WinPygame   ] trying without antialiasing
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 18.0.5>
[INFO   ] [GL          ] OpenGL vendor <X.Org>
[INFO   ] [GL          ] OpenGL renderer <AMD Radeon R7 Graphics (CARRIZO / DRM 3.25.0 / 4.17.2-200.fc28.x86_64, LLVM 6.0.0)>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event4
[INFO   ] [MTD         ] Read event from </dev/input/event4>
[INFO   ] [Base        ] Start application main loop
[WARNING] [MTD         ] Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "eventsapp/main.py", line 102, in <module>
     EventsApp().run()
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/app.py", line 828, in run
     runTouchApp()
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 403, in mainloop
     self._mainloop()
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 289, in _mainloop
     EventLoop.idle()
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/base.py", line 342, in idle
     self.dispatch_input()
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/base.py", line 293, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1109, in kivy._event.EventObservers._dispatch
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/lang/builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 34, in <module>
   File "/home/philomath/PyCon-Mobile-App/eventsapp/uix/screens/welcomescreen.py", line 58, in on_press_schedule
     app.load_screen('ScheduleScreen', manager=manager)
   File "eventsapp/main.py", line 89, in load_screen
     manager.current = screen
   File "kivy/weakproxy.pyx", line 33, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 478, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 516, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 571, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1225, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1131, in kivy._event.EventObservers._dispatch
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/uix/screenmanager.py", line 1048, in on_current
     self.transition.start(self)
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/uix/screenmanager.py", line 377, in start
     self.screen_in.dispatch('on_pre_enter')
   File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch
   File "/home/philomath/PyCon-Mobile-App/eventsapp/uix/screens/schedulescreen.py", line 98, in on_pre_enter
     self.add_dated_tabs(scheduledatedtab, day, halls, data)
   File "/home/philomath/PyCon-Mobile-App/eventsapp/uix/screens/schedulescreen.py", line 40, in add_dated_tabs
     hall = Factory.HallTabbedPanelItem(text=hall_name)
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/uix/behaviors/togglebutton.py", line 84, in __init__
     super(ToggleButtonBehavior, self).__init__(**kwargs)
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/uix/behaviors/button.py", line 121, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/uix/label.py", line 277, in __init__
     super(Label, self).__init__(**kwargs)
   File "/home/philomath/virtualenvs/kivy_apps/lib/python2.7/site-packages/kivy/uix/widget.py", line 337, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy/_event.pyx", line 273, in kivy._event.EventDispatcher.__init__
   File "kivy/properties.pyx", line 478, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 513, in kivy.properties.Property.set
 ValueError: HallTabbedPanelItem.text accept only str



```

**Comment by philo-math** [comment]
Issue was Python2.7 related. No issue in python3.6.
